FROM node:18 AS build

WORKDIR /app

RUN echo "=== NODE ==="
RUN node -v

RUN echo "=== NPM ==="
RUN npm -v

RUN echo "=== PROXY ==="
RUN env | grep -i proxy || true

RUN echo "=== NPM CONFIG ==="
RUN npm config list

COPY package*.json ./

RUN npm cache clean --force

RUN npm ci

RUN echo "=== VITE ==="
RUN npx vite --version

COPY . .

RUN npm run build


FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
