FROM node:18 AS build

WORKDIR /app

COPY package*.json ./

RUN env | grep NODE

RUN npm config get production

RUN npm install

COPY . .

RUN ls -l node_modules/.bin

RUN npm list vite

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
